version: '3.9'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_NAME
      - DB_HOST
      - DB_PORT
      - NODE_ENV
      - JWT_SECRET
      - JWT_EXPIRES_IN
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run migrate && npm run seed && npm run dev"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"